# Generated by Django 5.0.2 on 2024-02-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_sig', models.CharField(max_length=10)),
                ('invoice_num', models.CharField(max_length=10)),
                ('invoice_date', models.DateField()),
                ('tax', models.IntegerField()),
                ('total', models.IntegerField()),
                ('invoice_check_code', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
    ]
