# Generated by Django 5.0.2 on 2024-03-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_filetool'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
