# Generated by Django 5.0.2 on 2024-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
